controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


# *********************une manière de faire les routes//////
# hello:
#     path: /hello
#     controller: App\Controller\HelloController::hello

# helloName:
#     path: /hello/{name}
#     controller: App\Controller\HelloController::helloName
